BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN

@foreach($data as $el)
{{$el -> id}}
@endforeach

BEGIN:VEVENT
SUMMARY:тестовове событие
DTSTART;TZID=America/New_York:20230214T103400
DTEND;TZID=America/New_York:20230214T103500
LOCATION:1000 Broadway Ave.\, Brooklyn
DESCRIPTION: Access-A-Ride to 900 Jay St.\, Brooklyn
STATUS:CONFIRMED
SEQUENCE:3
BEGIN:VALARM
TRIGGER:-PT10M
DESCRIPTION:Pickup Reminder
ACTION:DISPLAY
END:VALARM
END:VEVENT

BEGIN:VEVENT
SUMMARY:тестовове событие 2
DTSTART;TZID=America/New_York:20230215T103400
DTEND;TZID=America/New_York:20230215T103500
LOCATION:900 Jay St.\, Brooklyn
DESCRIPTION: Access-A-Ride to 1000 Broadway Ave.\, Brooklyn
STATUS:CONFIRMED
SEQUENCE:3
BEGIN:VALARM
TRIGGER:-PT10M
DESCRIPTION:Pickup Reminder
ACTION:DISPLAY
END:VALARM
END:VEVENT

END:VCALENDAR